from http.server import BaseHTTPRequestHandler
import json
import yt_dlp
import os
import urllib.request

BROWSERLESS_TOKEN = os.environ.get('BROWSERLESS_TOKEN', 'demo-token')

class handler(BaseHTTPRequestHandler):
    def do_POST(self):
        try:
            content_length = int(self.headers['Content-Length'])
            body = self.rfile.read(content_length)
            data = json.loads(body.decode('utf-8'))

            video_url = data.get('url')
            if not video_url:
                self.send_error_response(400, 'Missing video URL')
                return

            # Step 1: Get YouTube cookies via Browserless bot
            print("Step 1: Getting cookies via Browserless...")
            cookies_content = self.get_youtube_cookies_browserless()

            # Step 2: Try all 5 methods WITH cookies
            methods = [
                self.method_1_android_ssl_bypass,
                self.method_2_ios_custom_headers,
                self.method_3_multi_client_fallback,
                self.method_4_tv_embedded,
                self.method_5_combined_ultimate,
            ]

            last_error = None
            for i, method in enumerate(methods, 1):
                try:
                    print(f"Trying Method {i} with cookies...")
                    result = method(video_url, cookies_content)
                    result['method_used'] = f'Method {i}'
                    result['method_name'] = method.__name__.replace('_', ' ').title()
                    result['cookies_used'] = len(cookies_content) > 0

                    self.send_response(200)
                    self.send_header('Content-type', 'application/json')
                    self.send_header('Access-Control-Allow-Origin', '*')
                    self.end_headers()
                    self.wfile.write(json.dumps(result).encode())
                    return
                except Exception as e:
                    last_error = str(e)
                    print(f"Method {i} failed: {e}")
                    continue

            # All methods failed
            self.send_error_response(500, f'All 5 methods failed. Last error: {last_error}')

        except Exception as e:
            self.send_error_response(500, f'Request error: {str(e)}')

    def get_youtube_cookies_browserless(self):
        """
        Get YouTube cookies using Browserless bot
        This navigates to YouTube and extracts all cookies
        """
        try:
            function_url = f'https://chrome.browserless.io/function?token={BROWSERLESS_TOKEN}'

            # JavaScript to get cookies from YouTube
            js_code = """
            module.exports = async ({ page }) => {
                try {
                    // Navigate to YouTube
                    await page.goto('https://www.youtube.com', {
                        waitUntil: 'networkidle2',
                        timeout: 30000
                    });

                    // Try to accept cookies dialog
                    try {
                        const acceptButton = await page.waitForSelector('button[aria-label*="Accept"], button[aria-label*="accept"], form[action*="consent"] button', { timeout: 5000 });
                        await acceptButton.click();
                        await page.waitForTimeout(2000);
                    } catch (e) {
                        // No dialog or already accepted
                    }

                    // Get all cookies
                    const cookies = await page.cookies();

                    // Convert to Netscape format
                    let netscapeCookies = '# Netscape HTTP Cookie File\\n';
                    netscapeCookies += '# Generated by Browserless bot\\n\\n';

                    for (const cookie of cookies) {
                        const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
                        const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
                        const path = cookie.path || '/';
                        const secure = cookie.secure ? 'TRUE' : 'FALSE';
                        const expiration = cookie.expires ? Math.floor(cookie.expires) : '0';

                        netscapeCookies += `${domain}\\t${flag}\\t${path}\\t${secure}\\t${expiration}\\t${cookie.name}\\t${cookie.value}\\n`;
                    }

                    return {
                        success: true,
                        cookies: netscapeCookies,
                        count: cookies.length
                    };
                } catch (error) {
                    return {
                        success: false,
                        error: error.message
                    };
                }
            };
            """

            req_data = {'code': js_code}
            req = urllib.request.Request(
                function_url,
                data=json.dumps(req_data).encode('utf-8'),
                headers={'Content-Type': 'application/json'}
            )

            with urllib.request.urlopen(req, timeout=45) as response:
                result = json.loads(response.read().decode('utf-8'))
                if result.get('success'):
                    print(f"✅ Got {result.get('count', 0)} cookies from Browserless")
                    return result.get('cookies', '')
                else:
                    print(f"⚠️ Browserless failed: {result.get('error')}")
                    return ''

        except Exception as e:
            print(f'❌ Cookie fetch error: {e}')
            return ''

    def extract_with_cookies(self, video_url, ydl_opts, cookies_content):
        """Helper to extract info with cookies"""
        import tempfile

        # Save cookies to temp file
        cookies_file = None
        if cookies_content:
            with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
                f.write(cookies_content)
                cookies_file = f.name

        try:
            if cookies_file:
                ydl_opts['cookiefile'] = cookies_file

            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(video_url, download=False)
                return info
        finally:
            # Cleanup temp file
            if cookies_file:
                try:
                    os.unlink(cookies_file)
                except:
                    pass

    def method_1_android_ssl_bypass(self, video_url, cookies_content):
        """METHOD 1: Android Client with SSL Bypass + Cookies"""
        ydl_opts = {
            'quiet': True,
            'no_warnings': True,
            'format': 'best[height<=720]',
            'socket_timeout': 30,
            'extractor_args': {
                'youtube': {
                    'player_client': ['android'],
                    'player_skip': ['webpage', 'configs'],
                }
            },
            'no_check_certificate': True,
        }

        info = self.extract_with_cookies(video_url, ydl_opts, cookies_content)

        return {
            'status': 'success',
            'title': info.get('title', 'Unknown'),
            'duration': info.get('duration', 0),
            'formats_count': len(info.get('formats', [])),
            'description': 'Android client with SSL bypass + Browserless cookies',
        }

    def method_2_ios_custom_headers(self, video_url, cookies_content):
        """METHOD 2: iOS Client with Custom Headers + Cookies"""
        ydl_opts = {
            'quiet': True,
            'no_warnings': True,
            'format': 'best[height<=720]',
            'socket_timeout': 30,
            'extractor_args': {
                'youtube': {
                    'player_client': ['ios', 'android'],
                    'player_skip': ['webpage'],
                }
            },
            'http_headers': {
                'User-Agent': 'com.google.ios.youtube/19.09.3 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)',
                'X-YouTube-Client-Name': '5',
                'X-YouTube-Client-Version': '19.09.3',
            },
            'no_check_certificate': True,
        }

        info = self.extract_with_cookies(video_url, ydl_opts, cookies_content)

        return {
            'status': 'success',
            'title': info.get('title', 'Unknown'),
            'duration': info.get('duration', 0),
            'formats_count': len(info.get('formats', [])),
            'description': 'iOS client with custom headers + Browserless cookies',
        }

    def method_3_multi_client_fallback(self, video_url, cookies_content):
        """METHOD 3: Multi-Client Fallback Chain + Cookies"""
        ydl_opts = {
            'quiet': True,
            'no_warnings': True,
            'format': 'best[height<=720]',
            'socket_timeout': 30,
            'extractor_args': {
                'youtube': {
                    'player_client': ['android', 'ios', 'tv_embedded', 'web'],
                    'player_skip': ['configs'],
                }
            },
            'http_headers': {
                'User-Agent': 'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36',
                'Accept-Language': 'en-US,en;q=0.9',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            },
            'no_check_certificate': True,
        }

        info = self.extract_with_cookies(video_url, ydl_opts, cookies_content)

        return {
            'status': 'success',
            'title': info.get('title', 'Unknown'),
            'duration': info.get('duration', 0),
            'formats_count': len(info.get('formats', [])),
            'description': 'Multi-client fallback chain + Browserless cookies',
        }

    def method_4_tv_embedded(self, video_url, cookies_content):
        """METHOD 4: TV Embedded Client + Cookies"""
        ydl_opts = {
            'quiet': True,
            'no_warnings': True,
            'format': 'best[height<=720]',
            'socket_timeout': 30,
            'extractor_args': {
                'youtube': {
                    'player_client': ['tv_embedded', 'android'],
                    'player_skip': [],
                }
            },
            'age_limit': 99,
            'no_check_certificate': True,
        }

        info = self.extract_with_cookies(video_url, ydl_opts, cookies_content)

        return {
            'status': 'success',
            'title': info.get('title', 'Unknown'),
            'duration': info.get('duration', 0),
            'formats_count': len(info.get('formats', [])),
            'description': 'TV embedded client + Browserless cookies',
        }

    def method_5_combined_ultimate(self, video_url, cookies_content):
        """METHOD 5: Combined Ultimate Method + Cookies"""
        ydl_opts = {
            'quiet': True,
            'no_warnings': True,
            'format': 'best[height<=720]',
            'socket_timeout': 45,
            'retries': 3,
            'fragment_retries': 3,
            'extractor_args': {
                'youtube': {
                    'player_client': ['android', 'ios', 'tv_embedded', 'web', 'mweb', 'android_creator'],
                    'player_skip': ['webpage', 'configs'],
                }
            },
            'http_headers': {
                'User-Agent': 'com.google.android.youtube/19.09.36 (Linux; U; Android 13) gzip',
                'X-YouTube-Client-Name': '3',
                'X-YouTube-Client-Version': '19.09.36',
                'Accept-Language': 'en-US,en;q=0.9',
                'Accept': '*/*',
                'Accept-Encoding': 'gzip, deflate',
            },
            'age_limit': 99,
            'no_check_certificate': True,
            'prefer_insecure': True,
        }

        info = self.extract_with_cookies(video_url, ydl_opts, cookies_content)

        return {
            'status': 'success',
            'title': info.get('title', 'Unknown'),
            'duration': info.get('duration', 0),
            'formats_count': len(info.get('formats', [])),
            'view_count': info.get('view_count', 0),
            'uploader': info.get('uploader', 'Unknown'),
            'description': 'Combined ultimate method + Browserless cookies (NUCLEAR OPTION)',
        }

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

    def send_error_response(self, code, message):
        self.send_response(code)
        self.send_header('Content-type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()
        self.wfile.write(json.dumps({'error': message}).encode())
