from http.server import BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
import json
import urllib.request
import os

BROWSERLESS_TOKEN = os.environ.get('BROWSERLESS_TOKEN', 'demo-token')

class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        try:
            # Parse query parameters
            parsed_path = urlparse(self.path)
            query_params = parse_qs(parsed_path.query)
            session_id = query_params.get('sessionId', [None])[0]

            if not session_id:
                self.send_response(400)
                self.send_header('Content-type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(json.dumps({'error': 'Missing sessionId'}).encode())
                return

            # Execute JavaScript to get cookies from the remote browser
            function_url = f'https://chrome.browserless.io/function?token={BROWSERLESS_TOKEN}'

            # JavaScript to extract cookies and convert to Netscape format
            js_code = """
            module.exports = async ({ page }) => {
                const cookies = await page.cookies();

                // Filter YouTube cookies
                const youtubeCookies = cookies.filter(cookie =>
                    cookie.domain.includes('youtube.com') ||
                    cookie.domain.includes('google.com')
                );

                // Convert to Netscape format
                let netscapeCookies = '# Netscape HTTP Cookie File\\n';
                netscapeCookies += '# This file was generated by yt-dlp web demo\\n\\n';

                for (const cookie of youtubeCookies) {
                    const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
                    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
                    const path = cookie.path || '/';
                    const secure = cookie.secure ? 'TRUE' : 'FALSE';
                    const expiration = cookie.expires ? Math.floor(cookie.expires) : '0';
                    const name = cookie.name;
                    const value = cookie.value;

                    netscapeCookies += `${domain}\\t${flag}\\t${path}\\t${secure}\\t${expiration}\\t${name}\\t${value}\\n`;
                }

                return {
                    cookies: netscapeCookies,
                    count: youtubeCookies.length,
                    status: 'success'
                };
            };
            """

            req_data = {
                'code': js_code,
                'context': {
                    'sessionId': session_id
                }
            }

            req = urllib.request.Request(
                function_url,
                data=json.dumps(req_data).encode('utf-8'),
                headers={'Content-Type': 'application/json'}
            )

            with urllib.request.urlopen(req, timeout=10) as response:
                result = json.loads(response.read().decode('utf-8'))

                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(json.dumps(result).encode())

        except Exception as e:
            self.send_response(500)
            self.send_header('Content-type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(json.dumps({
                'error': str(e),
                'status': 'error'
            }).encode())
